version: '3'  # Cambiado a la versión 3 para compatibilidad con la definición del servicio oracle-db

services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@localhost:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=prueba
      - SPRING_DATASOURCE_PASSWORD=prueba
    restart: always

  oracle-db:
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_RANDOM_PASSWORD=true
      - APP_USER=prueba
      - APP_USER_PASSWORD=prueba
      #- ORACLE_PDB=prueba
    #  - ORACLE_PASSWORD=prueba
      #- ORACLE_PWD=prueba
     # - ORACLE_CHARACTERSET=AL32UTF8
      #- ORACLE_EDITION=XE  # Oracle Edition (EE for Enterprise Edition)
    #volumes:
     # - oracle_data:/opt/oracle/oradata  # Persistencia de datos entre reinicios del contenedor

    #options: >-
     #   --health-cmd healthcheck.sh
      #  --health-interval 10s
       # --health-timeout 5s
        #--health-retries 10
#volumes:
 # oracle_data:
  #  driver: local